### ISSUE TITLE
setzone not working (no Message in the logs)

### ISSUE THREAD

**Issue by fanningert** [MTrab/landroid_cloud#112]
### Environment:
Home Assistant 2022.4.7
Landroid_cloud version: 1.8.7
Operation system: Home Assistant OS - core-2022.4.7

Mower: Worx Landroid M500 WE141E

## Configuration

Switch code
```yaml
      mower_zone2:
        unique_id: mower_zone2
        value_template: "{{ is_state_attr('sensor.landroid_poolbereich_status', 'mowing_zone', 1) }}"
        turn_on:
          service: landroid_cloud.setzone
          data:
            id: "{{ state_attr('sensor.landroid_poolbereich_status','id') }}"
            zone: 1
        turn_off:
          service: landroid_cloud.setzone
          data:
            id: "{{ state_attr('sensor.landroid_poolbereich_status','id') }}"
            zone: 1
        icon_template: mdi:numeric-2-box
```
Here the information from senor landroid_poolbereich_status
```
id: 999999
total_blade_time: 4482
current_blade_time: 4482
blade_time_reset: null
work_time: 4826
distance: 57547
status_id: 1
last_update: 10:35:07 30/04/2022
rssi: -66
yaw: 178.8
roll: -2.6
pitch: 0.6
raindelay: 180
timeextension: 0
firmware_version: 3.26
serial: xxxxxxxxxxx
mac: xxxxxxxxxx
schedule_enabled: true
partymode_enabled: false
mowing_zone: 3
accessories:
  ultrasonic: true
locked: false
friendly_name: Poolbereich status
```

## Describe the bug
When I click on the switch, the zone don't change. (I waited 5 minutes) In the logs and also debugging logs are no error visible.
Other interessing status is that the attribute "schedule_enabled" is showing as "true", but in the APP the sheduling is disabled.

## Debug log

no error found in the debug logs
