### ISSUE TITLE
After update from version 2.0.3 to 2.1.3 the zone information are empty.

### ISSUE THREAD

**Issue by fanningert** [MTrab/landroid_cloud#181]
### Environment:
- Home Assistant version: 2022.05.3
- Landroid_cloud version: 2.1.3
- Operation system: HAOS

## Describe the bug
After update from version 2.0.3 to 2.1.3 the zone information are empty.

Here vaccum status output.
```yaml
battery_level: 69
battery_icon: mdi:battery-charging-60
accessories:
  ultrasonic: true
battery:
  cycles:
    total: 0
    current: 0
    reset_at: null
    reset_time: null
blades:
  total_on: 11205
  reset_at: 0
  reset_time: null
  current_on: 11205
error:
  id: -1
  description: unknown
firmware:
  auto_upgrade: true
  version: 3.26
locked: false
mac_address: xxxxx
model: Landroid M500
online: true
orientation:
  pitch: -0.5
  roll: -3.4
  yaw: 6.2
rain_sensor:
  delay: 0
schedule:
  time_extension: 0
  active: true
  auto_schedule:
    settings: {}
    enabled: null
serial_number: 2020301xxxxxxxxx
status_info:
  id: -1
  description: unknown
time_zone: Europe/Vienna
zone:
  current: null
  index: null
  indicies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  starting_point:
    - 0
    - 0
    - 0
    - 0
capabilities:
  - One-Time-Schedule
  - Party Mode
  - Motor Torque
mqtt_connected: true
supported_landroid_features: 4671
device_class: landroid_cloud__state
friendly_name: WorxWR141E
supported_features: 12500
party_mode_enabled: false
rssi: -80
statistics:
  worktime_blades_on: 11213
  distance: 142995
  worktime_total: 12099
torque: 0
state_updated_at: '2022-07-01T08:45:42+02:00'
```
