### ISSUE TITLE
Configuring time_extension doesn't work for negative values

### ISSUE THREAD

**Issue by TArentoft** [MTrab/landroid_cloud#198]
### Environment:
- Home Assistant 2022.7.3
- Supervisor 2022.07.0
- Operating System 8.2
- Landroid_cloud version: 2.2.0

## Configuration

```yaml

service: landroid_cloud.config
data:
  timeextension: -10
target:
  device_id: [XXX]
  entity_id: vacuum.[xxx]

```

## Describe the bug
Using landroid_cloud.config to set timeextension doesn't work for negative values. Positive values, including zero, works fine. No error, the value just isn't applied on the robot.

## Debug log
no error
