### ISSUE TITLE
Rain Sensor is not updating anymore

### ISSUE THREAD

**Issue by prof7bit** [MTrab/landroid_cloud#205]
Before the update that rearranged all the state attributes this used to work. 

I have broken it out with a template sensor and then I could use that like a regular rain sensor, it used to work even when rain delay was disabled and the mower was docked. Now it is always false, even if I intentionally pour water onto it.

**Comment by MTrab** [comment]
Can you please share the code for your template sensor?
Can't remember that this have ever been an attribute.
Rain Delay (sensor triggered) are presented as an error (attribute error.id = 5 indicates that the mower is stoppe because of a triggered rain sensor)

**Comment by prof7bit** [comment]
Wait a moment, I just looked and it referred to attribute `rain_sensor_triggered`, I think this is probably wrong, I just wonder why home assistand did not grey out the sensor as unavailable like it did with all the other attributes that changed names. 

I am going to investigate later today and report back, if it was my fault I will close this bug.

**Comment by prof7bit** [comment]
It was my fault, this bug is invalid!

This was the only sensor where I forgot to change the referenced attribute after the attributes have been renamed recently, it was still referring to `rain_sensor_triggered`. For some reason I did not see any complaint from HomeAssistant, it did not gray out the sensor as "unavailable" as it does with normal (non-binary) sensors, it appeared as operational with a state of "dry" (false).

I changed the template sensor like so:

````yaml
- binary_sensor:
    - unique_id: herbert_rain
      state: "{{ state_attr('vacuum.herbert', 'rain_sensor').triggered }}"
      device_class: moisture
      attributes:      
        friendly_name: "Herbert Regensensor"
 ````

And immediately it started working.

Pouring water onto the sensor will update it on the next 10 minute cycle, even if the rain delay in the mower is disabled. So I can use it like a regular standalone rain sensor.

I am closing this bug, i am sorry having wasted your time with an invalid bug that was actually my own fault.
