### ISSUE TITLE
Blades_current_on attribute only updates irregular (versions > 2.0.3)

### ISSUE THREAD

**Issue by mdkeil** [MTrab/landroid_cloud#207]
### Environment:
- Home Assistant 2022.7.4
- Landroid_cloud version: 2.2.1
- Operation system: Docker Container 

## Configuration
```
image: default
compact_view: false
show_status: true
show_name: true
show_toolbar: true
type: custom:landroid-card
entity: vacuum.graspirat
stats:
  default:
    - attribute: blades.total_on
      subtitle: Total blade time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: blades.current_on
      subtitle: Cur. blade time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: statistics.worktime_total
      subtitle: Work time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: statistics.distance
      value_template: '{{ (value | float(0) / 1000) | round(2) }}'
      unit: km
      subtitle: Distance
    - attribute: torque
      subtitle: Torque
  mowing:
    - attribute: orientation.yaw
      subtitle: Yaw
      unit: °
    - attribute: orientation.roll
      subtitle: Roll
      unit: °
    - attribute: orientation.pitch
      subtitle: Pitch
      unit: °
    - attribute: torque
      subtitle: Torque
    - attribute: blades.current_on
      subtitle: Current blade time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
```

##
With all versions > 2.0.3 I have the problem, that the blades current_on attribute often don't update once a day. All the other attribute-values updates very quickly.
