### ISSUE TITLE
Schedule service is not supported by this device (anymore)

### ISSUE THREAD

**Issue by valentingc** [MTrab/landroid_cloud#228]
### Environment:
- Home Assistant version: 2022.7.1
- Landroid_cloud version: 2.2.2
- Operation system: Core / Docker

## Configuration

```yaml

-> Legacy option not used.
```

## Describe the bug
The schedule service does not work for me anymore. I can confirm that it has worked for previous versions < 2.1.0 or so (don't remember exactly which version but I know it worked). Apparently, the mower does not support the service (anymore).

The mower is a Worx WR165E mower that definitely supports the service (and as I said, it worked previously). Seems to be some kind of mapping error or so.

This is the service call:

```
service: landroid_cloud.schedule
data:
  sunday_end: '16:00:00'
  monday_start: '12:00:00'
  monday_end: '16:00:00'
  monday_boundary: true
  tuesday_start: '12:00:00'
  tuesday_end: '16:00:00'
  sunday_start: '12:00:00'
  saturday_end: '16:00:00'
  saturday_start: '12:00:00'
  friday_end: '16:00:00'
  friday_start: '12:00:00'
  thursday_end: '16:00:00'
  wednesday_end: '16:00:00'
  thursday_start: '12:00:00'
  wednesday_start: '12:00:00'
  wednesday_boundary: true
  friday_boundary: true
  sunday_boundary: true
target:
  entity_id: vacuum.mower

```
## Debug log

```text
Logger: custom_components.landroid_cloud.services
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 11:44:19 AM (2 occurrences)
Last logged: 11:44:19 AM

(Mower, Service Call) The called service, schedule, is not supported by this device!
(Mower, Service Call) Supported services for this device: ['lock', 'setzone', 'refresh', 'restart', 'config', 'send_raw', 'edgecut', 'partymode', 'ots', 'torque']
```
Didn't really find anything else besides the error above - is there any specific log I can send you to help debug?
