### ISSUE TITLE
Showing attributes as a part of entity card

### ISSUE THREAD

**Issue by Lundte** [MTrab/landroid_cloud#250]
**Is your feature request related to a problem? Please describe.**
I would like to pull some of the sensor informations there is kept in attributes. I have tried to put them on as shown: 

type: entities
entities:
  - vacuum.gump
  attribute: battery_temperature
title: Robotplæneklipper

But it doesnt work.

**Describe the solution you'd like**
I would like to use / pull the attributes out to the front of the entity card

I have attached a photo of the attributes I'm talking about
Looking forward to hear from you.

<img width="387" alt="Screen Shot 2022-08-23 at 14 07 07" src="https://user-images.githubusercontent.com/39701538/186154165-e9840e5d-e77f-4d49-8b3c-c9c782f962d2.png">

**Comment by Miicroo** [comment]
@Lundte The Battery-object used in landroid_cloud is its own class with internal properties and thus you can't fetch it using the attributes in the entities card. Instead you can use a templated sensor:
```
template:
  - sensor:
      - name: "Gump battery temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('vacuum.gump', 'battery').temperature }}"
```

This will give you a new sensor, `sensor.gump_battery_temperature`, which has the correct temperature
