### ISSUE TITLE
Service send_raw command doesn't work

### ISSUE THREAD

**Issue by pierceppdh** [MTrab/landroid_cloud#253]
### Environment:
- Home Assistant version: 2022.7.3
- Landroid_cloud version: 2.3.1
- Operation system: Docker

## Configuration

```yaml
service: landroid_cloud.send_raw
data:
  json:
    cmd: 1

or 
service: landroid_cloud.send_raw
data:
  json: "{'cmd': 1}"



```

## Describe the bug
Trying to send a raw command to the Landroid via dev. tool-services in home assistant but I get an "unknown error" in home assistant.
I'm trying to send the string "{'cmd': 1}". I have tried different format for the string but none of them are working. When trying to past the example it provides the following:
service: landroid_cloud.send_raw
data:
  json:
    cmd: 1

Which doesn't work either as this is not a string.

## Debug log

```text


```
