### ISSUE TITLE
Exposing the vacuum to homekit has no function and the state is not updating

### ISSUE THREAD

**Issue by Phoenix-DH** [MTrab/landroid_cloud#401]
### Describe the issue

Exposing the vacuum to homekit has no function and the state is not updating.
Hit the button will have no effect.
The button always looks like the device is off, although when moving.

Is this by default and you have to create an own switch?

### What version of Home Assistant Core has the issue?

core-2023.6.3

### What version of the Landroid Cloud integration do you have installed

latest

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M700

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
Got absolutely no idea.
Don't use HomeKit, don't have homekit

**Comment by Phoenix-DH** [comment]
Ah okay, I was wondering if someone else has the same. I think so.
Wait for some responses and try to create an own switch when I got the time.
I think it should be no big deal.

I have othe vacuums exposes, real vacuums and those are working. So I try to understand the relations. I think your implementation is using different states … mowing = cleaning …

That may be the case that the switch is always off and never turning on…

**Comment by Phoenix-DH** [comment]
I think this should roughly do the trick (including party mode switch):

```
switch:
  - platform: template
    switches:
      james_partymode:
        value_template: "{{ is_state_attr('vacuum.james', 'party_mode_enabled', true) }}"
        turn_on:
          service: landroid_cloud.partymode
          data:
            party_mode_enabled: true
          target:
            entity_id: vacuum.james
        turn_off:
          service: landroid_cloud.partymode
          data:
            party_mode_enabled: false
          target:
            entity_id: vacuum.james
        unique_id: "james_partymode"
      james_mowing:
        value_template: "{{ is_state('vacuum.james', 'mowing') }}"
        turn_on:
          service: vacuum.turn_on
          data: {}
          target:
            entity_id: vacuum.james
        turn_off:
          service: vacuum.turn_off
          data: {}
          target:
            entity_id: vacuum.james
        unique_id: "james_mowing"
```
