### ISSUE TITLE
Device is not updating after a while

### ISSUE THREAD

**Issue by nbai777** [MTrab/landroid_cloud#615]
### Describe the issue

After a while the device does not updates itself in HA, and I'm unable to send command to the lawnmower.
This happens sometimes after a few hours, sometimes after days. If I reload the integration it fixes itself but only for limited time again.

### What version of Home Assistant Core has the issue?

core-2024.4.2

### What version of the Landroid Cloud integration do you have installed

v5.0.4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid WR130E

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-57a834ba16175855420d56dbe839fb24 (1).json](https://github.com/MTrab/landroid_cloud/files/15283695/config_entry-landroid_cloud-57a834ba16175855420d56dbe839fb24.1.json)

### Relevant log entries

```txt
None
```

**Comment by Hrast100** [comment]
I have same problem. 
And also have a problem with and automation. I want that go on a dock when battery is 15% and not 9% (default value). 

Home Assistant Core
Installed version
2024.5.2

Landroid L1000 (WR147E.1)
by Worx
Firmware: 3.32.0+1

Sensors
Battery
99%
Daily Progress
100%
Last Update
Yesterday
-----------------------------------
Trigger
Robot Battery battery level changes
Above
18%
Below
20%

**Comment by MTrab** [comment]
Have been trying for a while to fix bugs like this - I do not see this when I test, so it's pretty difficult to fix.

I have no idea what I can do, unfortunately

**Comment by nbai777** [comment]
I see, but you know since I posted this issue the integration is working fine without any problem :)

**Comment by tomek550** [comment]
Having same issue on my WR157. Are there some debug logs I could check?

**Comment by sithmein** [comment]
I had similar problems when my internet connection dropped.
I have created an automation that reloads the integration after one hour with no update.
```
alias: Restart Landroid Cloud Integration
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.mower_last_update
    to: null
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition: []
action:
  - service: homeassistant.reload_config_entry
    target:
      device_id: 99c934e66ccd6e6c211515a345965aaa
    data:
      entry_id: abc8adb6e3837e5375be0b7d5474dc16
mode: single
```
