### ISSUE TITLE
[Bug] Partymode api call does not work and results to an error log (Worx Landroid M500)

### ISSUE THREAD

**Issue by MrockHunter12** [MTrab/landroid_cloud#83]
### Environment

- Home Assistant version: 2021.8.1
- Landroid_cloud version: 1.8.0
- Operation system: HA /raspberry 4/ docker 

### Model
- Model: Worx Landroid M 500
![image](https://user-images.githubusercontent.com/88487145/139541841-149d11de-007c-482d-bd6a-28a5043fa19a.png)

## Configuration in HA

```yaml

# Activates party mode
  landroid_partymode:
    alias: Landroid Party Mode
    sequence:
      service: landroid_cloud.partymode
      data:
        id: "{{ state_attr('sensor.landroid_m_status','id') }}"

```

## Description

Calling partymode service results in an error log and is not executed.

## Debug log

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/landroid_cloud/__init__.py:286
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:24:00 (1 occurrences)
Last logged: 18:24:00

[2955675248] 'enable'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 278, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 382, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 409, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/landroid_cloud/__init__.py", line 286, in handle_partymode
    cli.partyMode(call.data["enable"])
KeyError: 'enable'

**Comment by MTrab** [comment]
Seems like you are missing a key.

Should be like this:

```yaml

# Activates party mode
  landroid_partymode:
    alias: Landroid Party Mode
    sequence:
      service: landroid_cloud.partymode
      data:
        id: "{{ state_attr('sensor.landroid_m_status','id') }}"
        enable: true

```

Or:

```yaml

# Activates party mode
  landroid_partymode:
    alias: Landroid Party Mode
    sequence:
      service: landroid_cloud.partymode
      data:
        id: "{{ state_attr('sensor.landroid_m_status','id') }}"
        enable: false

```

Will look into better errorhandling for next release.
