### ISSUE TITLE
HA 2022.3 (Beta) Breaks Landroid Cloud 

### ISSUE THREAD

**Issue by KNXBroker** [MTrab/landroid_cloud#92]
## Environment:

- Home Assistant version: 2022.3.0b4
- Landroid_cloud version: 1.8.1
- Operation system: HAOS

## Configuration

```

# Landroid Integration
landroid_cloud:
  - email: !secret email
    password: !secret robbi_password

```

## Describe the bug

Installed HA 2022.3b3 --> Landroid integration can no longer be loaded. See logs. 

## Debug log

```
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 08:09:46 (9 occurrences)
Last logged: 08:57:20

Unable to install package pyworxcloud==1.4.11: ERROR: Cannot install pyworxcloud==1.4.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
